# Verwende ein offizielles Python-Image als Basis
FROM python:3.8-slim

# Set
# Installiere alle benötigten Pakete
RUN pip install 

# Kopiere den Rest des Codes in den Container
COPY . .

# Befehl, der ausgeführt wird, wenn der Container startet
CMD ["python", "./your-model-script.py"]

