version: '3.8'

services:
  ml_service1:
    build: ./ml1
    volumes:
      - ./ml1/data:/app/data
    command: python main.py

  db1:
    image: postgres:latest
    environment:
      POSTGRES_DB: db1
      POSTGRES_USER: user1
      POSTGRES_PASSWORD: password1
    volumes:
      - ./ml1/dbdata:/var/lib/postgresql/data
    ports:
      - "54321:5432"

  ml_service2:
    build: ./ml2
    volumes:
      - ./ml2/data:/app/data
    command: python main.py

  db2:
    image: postgres:latest
    environment:
      POSTGRES_DB: db2
      POSTGRES_USER: user2
      POSTGRES_PASSWORD: password2
    volumes:
      - ./ml2/dbdata:/var/lib/postgresql/data
    ports:
      - "54322:5432"

  ml_service3:
    build: ./ml3
    volumes:
      - ./ml3/data:/app/data
    command: python main.py

  db3:
    image: postgres:latest
    environment:
      POSTGRES_DB: db3
      POSTGRES_USER: user3
      POSTGRES_PASSWORD: password3
    volumes:
      - ./ml3/dbdata:/var/lib/postgresql/data
    ports:
      - "54323:5432"

  ml_service4:
    build: ./ml4
    volumes:
      - ./ml4/data:/app/data
    command: python main.py

  db4:
    image: postgres:latest
    environment:
      POSTGRES_DB: db4
      POSTGRES_USER: user4
      POSTGRES_PASSWORD: password4
    volumes:
      - ./ml4/dbdata:/var/lib/postgresql/data
    ports:
      - "54324:5432"

  ml_service5:
    build: ./ml5
    volumes:
      - ./ml5/data:/app/data
    command: python main.py

  db5:
    image: postgres:latest
    environment:
      POSTGRES_DB: db5
      POSTGRES_USER: user5
      POSTGRES_PASSWORD: password5
    volumes:
      - ./ml5/dbdata:/var/lib/postgresql/data
    ports:
      - "54325:5432"

volumes:
  dbdata1:
  dbdata2:
  dbdata3:
  dbdata4:
  dbdata5:
